In [1]:
import pandas as pd

df = pd.read_csv("layoffs.csv")

df.head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Trustly,"Stockholm, Non-U.S.",200.0,9/17/2026,NaN,Finance,https://tech.eu/2026/09/17/swedish-fintech-tru...,Acquired,28.0,Sweden,9/17/2026
1,Bluevine,"Bengaluru, Non-U.S.",80.0,9/17/2026,NaN,Finance,https://www.ndtv.com/offbeat/team-of-80-indian...,Unknown,769.0,India,9/17/2026
2,Pulley,SF Bay Area,NaN,9/15/2026,1.0,Finance,https://www.businessinsider.com/pulley-shuts-d...,Series B,50.0,United States,9/16/2026
3,Oracle,SF Bay Area,NaN,9/14/2026,NaN,Other,https://www.businessinsider.com/oracle-begins-...,Post-IPO,NaN,United States,9/16/2026
4,Bitcoin Suisse,"Zurich, Non-U.S.",60.0,9/11/2026,0.5,Crypto,https://www.reuters.com/business/world-at-work...,Series A,NaN,Switzerland,9/14/2026

In [2]:
df.head(10)

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Trustly,"Stockholm, Non-U.S.",200.0,9/17/2026,NaN,Finance,https://tech.eu/2026/09/17/swedish-fintech-tru...,Acquired,28.0,Sweden,9/17/2026
1,Bluevine,"Bengaluru, Non-U.S.",80.0,9/17/2026,NaN,Finance,https://www.ndtv.com/offbeat/team-of-80-indian...,Unknown,769.0,India,9/17/2026
2,Pulley,SF Bay Area,NaN,9/15/2026,1.0,Finance,https://www.businessinsider.com/pulley-shuts-d...,Series B,50.0,United States,9/16/2026
3,Oracle,SF Bay Area,NaN,9/14/2026,NaN,Other,https://www.businessinsider.com/oracle-begins-...,Post-IPO,NaN,United States,9/16/2026
4,Bitcoin Suisse,"Zurich, Non-U.S.",60.0,9/11/2026,0.5,Crypto,https://www.reuters.com/business/world-at-work...,Series A,NaN,Switzerland,9/14/2026
5,Booksy,"Warsaw, Non-U.S.",200.0,9/10/2026,0.2,Consumer,https://www.linkedin.com/posts/sbatory_today-i...,Series B,204.0,Poland,9/14/2026
6,PhonePe,SF Bay Area,7.0,9/10/2026,NaN,Finance,https://timesofindia.indiatimes.com/business/i...,Acquired,3200.0,United States,9/14/2026
7,Neo Financial,"Calgary, Non-U.S.",102.0,9/8/2026,0.1,Finance,https://www.linkedin.com/pulse/important-chang...,Series D,544.0,Canada,9/9/2026
8,Samsung,"Gurugram, Non-U.S.",80.0,9/8/2026,NaN,Hardware,https://timesofindia.indiatimes.com/business/i...,Post-IPO,NaN,India,9/9/2026
9,Harrison.ai,"Melbourne, Non-U.S.",NaN,9/7/2026,NaN,Healthcare,https://www.abc.net.au/news/2026-09-08/harriso...,Series C,253.0,Australia,9/9/2026

In [3]:
df.shape

(4608, 11)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4608 entries, 0 to 4607
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4608 non-null   object
 1   location             4607 non-null   object
 2   total_laid_off       3010 non-null   float64
 3   date                 4608 non-null   object
 4   percentage_laid_off  2886 non-null   float64
 5   industry             4606 non-null   object
 6   source               4605 non-null   object
 7   stage                4600 non-null   object
 8   funds_raised         4059 non-null   float64
 9   country              4606 non-null   object
 10  date_added           4608 non-null   object
dtypes: float64(3), object(8)
memory usage: 396.1+ KB

In [5]:
df.describe(include="all")

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
count,4608,4607,3010.000000,4608,2886.000000,4606,4605,4600,4059.000000,4606,4608
unique,2988,271,NaN,1314,NaN,30,4345,16,NaN,66,1100
top,Amazon,SF Bay Area,NaN,4/2/2020,NaN,Finance,Internal memo,Post-IPO,NaN,United States,11/17/2022
freq,24,1141,NaN,27,NaN,549,106,1115,NaN,2897,45
mean,NaN,NaN,309.777741,NaN,0.296115,NaN,NaN,NaN,909.286547,NaN,NaN
std,NaN,NaN,1112.244640,NaN,0.306948,NaN,NaN,NaN,4927.505050,NaN,NaN
min,NaN,NaN,3.000000,NaN,0.000000,NaN,NaN,NaN,0.700000,NaN,NaN
25%,NaN,NaN,40.000000,NaN,0.100000,NaN,NaN,NaN,55.000000,NaN,NaN
50%,NaN,NaN,90.000000,NaN,0.170000,NaN,NaN,NaN,176.000000,NaN,NaN
75%,NaN,NaN,200.000000,NaN,0.330000,NaN,NaN,NaN,484.000000,NaN,NaN
max,NaN,NaN,22000.000000,NaN,1.000000,NaN,NaN,NaN,121900.000000,NaN,NaN

In [6]:
df.isnull().sum()

company                   0
location                  1
total_laid_off         1598
date                      0
percentage_laid_off    1722
industry                  2
source                    3
stage                     8
funds_raised            549
country                   2
date_added                0
dtype: int64

In [7]:
df.isnull().mean() * 100

company                 0.000000
location                0.021701
total_laid_off         34.678819
date                    0.000000
percentage_laid_off    37.369792
industry                0.043403
source                  0.065104
stage                   0.173611
funds_raised           11.914062
country                 0.043403
date_added              0.000000
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df[df["total_laid_off"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
2,Pulley,SF Bay Area,NaN,9/15/2026,1.0,Finance,https://www.businessinsider.com/pulley-shuts-d...,Series B,50.0,United States,9/16/2026
3,Oracle,SF Bay Area,NaN,9/14/2026,NaN,Other,https://www.businessinsider.com/oracle-begins-...,Post-IPO,NaN,United States,9/16/2026
9,Harrison.ai,"Melbourne, Non-U.S.",NaN,9/7/2026,NaN,Healthcare,https://www.abc.net.au/news/2026-09-08/harriso...,Series C,253.0,Australia,9/9/2026
13,Hale,"Berlin, Non-U.S.",NaN,9/3/2026,1.0,Healthcare,https://femtechinsider.com/pelvic-pain-startup...,Seed,1.0,Germany,9/4/2026
14,Orionx,"Santiago, Non-U.S.",NaN,9/3/2026,1.0,Crypto,https://cryptobriefing.com/orionx-shuts-down-7...,Series A,NaN,Chile,9/7/2026
...,...,...,...,...,...,...,...,...,...,...,...
4592,Vacasa,Portland,NaN,3/20/2020,NaN,Travel,https://www.bizjournals.com/portland/news/2020...,Series C,526.0,United States,3/28/2020
4597,Anyvision,"Tel Aviv, Non-U.S.",NaN,3/19/2020,NaN,Security,https://ipvm.com/reports/anyvision-20-layoffs,Series A,74.0,Israel,3/30/2020
4598,Popin,New York City,NaN,3/19/2020,1.0,Fitness,https://www.businessinsider.com/fitness-app-po...,Unknown,13.0,United States,4/6/2020
4599,Tuft & Needle,Phoenix,NaN,3/19/2020,NaN,Retail,https://www.theverge.com/2020/3/19/21185840/tu...,Acquired,NaN,United States,4/5/2020
4603,Service,Los Angeles,NaN,3/16/2020,1.0,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["month_name"] = df["date"].dt.month_name()

In [14]:
df["country"] = df["country"].str.strip()

In [15]:
print(df["country"])

0              Sweden
1               India
2       United States
3       United States
4         Switzerland
            ...
4603    United States
4604    United States
4605    United States
4606    United States
4607    United States
Name: country, Length: 4608, dtype: object

In [16]:
Q1 = df["total_laid_off"].quantile(0.25)
Q3 = df["total_laid_off"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [17]:
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)

Q1: 40.0
Q3: 200.0
IQR: 160.0
Lower Bound: -200.0
Upper Bound: 440.0